USE SKYTUS;
SELECT * FROM STUDENT;

#COUNT NUMBER OF STUDENT IN TABLE
SELECT COUNT(*) FROM STUDENT;

#FIND A AVRAGE MARKS OF STUDENT
SELECT AVG(MARKS) FROM STUDENT;

#FIND LOWER MARKS IN STUDENT TABLE
SELECT MIN(MARKS) FROM STUDENT;

#FIND HIGHEST MARKS IN STUDENT TABLE
SELECT MAX(MARKS) FROM STUDENT;

#FIND DEPARTMENT WISE AVRAGE MARKS
#FOR COMPUTER DEPARTMENT
SELECT AVG(MARKS) FROM STUDENT WHERE DEPARTMENT="COMPUTER";

#FOR ELECTRIC DEPARTMENT
SELECT AVG(MARKS) FROM STUDENT WHERE DEPARTMENT="ELECTRIC";

#FOR CSE DEPARTMENT 
SELECT AVG(MARKS) FROM STUDENT WHERE DEPARTMENT="CSE";

#FOR CIVIL DEPARTMENT
SELECT AVG(MARKS) FROM STUDENT WHERE DEPARTMENT="CIVIL";

#FOR IT DEPARTMENT 
SELECT AVG(MARKS) FROM STUDENT WHERE DEPARTMENT="IT";

#FIND DEPARTMENT NAME WHERE IT MARKS AVRGE IS GRETER THEN 70
SELECT  DEPARTMENT,AVG(MARKS) FROM STUDENT GROUP BY DEPARTMENT HAVING AVG(MARKS)>70;